---
title: "Ranier, 20 anos"
---

Baseado no caso Ranier descrito por Klaus Conrad no seu livro Esquizofrenia Incipiente [@conrad1963].

Ranier N, nascido em 1921. Deu entrada no hospital psiquiátrico no dia 29 de janeiro de 1941, com 20 anos de idade. Apresentava um grave delírio de referência. Acreditava que todos sabiam seus pensamentos, se mostrava bastante desconfiado e as vezes ficava agitado. Seu estado melhorou lentamente ao longo de 8 semanas de internação. Depois de melhorar contou como seu quadro se desenvolveu.

Começou a trabalhar como militar no exército alemão em 1940. Desejava seguir carreira de oficial, mas tinha receio de não conseguir. Logo começou a perceber que “havia algo estranho”, mas não sabia o que. Aos poucos começou a notar “rumores” de que ele iria ser o chefe da companhia. Ouvia esses rumores sobre o próximo chefe e, embora seu nome não fosse dito, passou a saber que se referiam a ele. Passou a sentir uma certa inimizade entre os colegas, que atribuiu a uma inveja. Pouco a pouco passou a sentir que todos se voltavam contra ele. 

Certo dia o capitão da companhia lhe disse “coloque-os em ordem, você é o responsável”. Ele percebeu que essa era uma alusão à sua ascensão profissional. 

Passou a não mais conversar com ninguém, pois temia a inveja dos colegas. Passou a notar que os colegas o observavam de forma estranha. Certa noite ouviu uma conversa de que os colegas o levariam para o campo, o amarrariam numa árvore e o queimariam com um ferro em brasa. Por medo, decidiu passar a noite em claro para poder se defender caso isso viesse a acontecer. Nessa noite começou a ouvir os passos de pessoas se aproximando ao redor de sua barraca, mas sempre que se levantava tudo ficava em silêncio novamente. Às vezes acendia a luz de sua barraca, mas não via nada, concluía então que todos se escondiam. Passou a noite toda acordado e vigilante. De manhã sentia haver uma certa inimizade entre ele e os colegas. Quando seu melhor amigo perguntou “o que se passa”, notou que todos se viraram para ele, “para ver como iria reagir”.

Sentia que tudo era uma ameaça. Percebeu que todos estava contra ele. Quando foi tomar banho, o jarro de água tinha desaparecido, quando se dirigia a algum lugar, alguém obstruía seu caminho. Passou a notar que faziam gestos para ele, sentia que eram todos grosseiros com ele. 

Percebeu que até seus melhores amigos passavam a se desviar dele aos poucos até o abandonarem totalmente e passou a se sentir completamente só.

Foi então levado até a enfermaria e, quando o tenente falava com ele, teve a sensação de que tramavam um plano para que ele deixasse de pensar em ser promovido. Queriam expô-lo ao ridículo em público. Foi então colocado em uma maca na enfermaria e teve de tomar um comprimido. Ele então pensou que essa medicação iria servir para provocar artificialmente um estado febril nele. 

Médicos e enfermeiros vieram em seguida e o levaram para um carro. Ele então passou a acreditar que queriam dar a ele uma nova oportunidade. Percebeu que estava sendo colocado a prova para poder finalmente um oficial do exército. Quando lhe ofereceram um cigarro pensou que havia ali alguma substância para paralisar sua vontade ou para enganá-lo de alguma forma. Em certo momento o motor do carro começou a falhar e ele então percebeu que isso era um sinal de que havia uma trama contra ele.  Em outro momento viu uma placa com a letra “N” e percebeu que esse era um sinal que significava “NÃO” e que queria dizer que ele não tinha mais esperanças. Ao passarem por uma cidade cunho nome significava “montanha acima” e uma lona verde e interpretou essas coisas como “sinais” de que havia novamente esperança. 

Quando chegou no hospital, enquanto aguardava, pode ouvir a voz de seu comandante e de seu coronel e teve a certeza de que tramavam seu assassinato, que o degolariam como a um animal. Quando encontrou com o médico essa certeza se confirmou quando viu uma seringa no bolso do paletó do médico. Quando foi colocado na cama da enfermaria teve a sensação de que estavam lendo seus pensamentos, que todos sabiam o que ele pensava.

Num momento em que estava sozinho, cortou os pulsos para se matar, pois “preferia morrer a viver aquele lento martírio”. Percebeu que, apesar de estar sozinho, as pessoas saberiam o que tinha feito por causa da transmissão de pensamento que estava sofrendo.

Alguns dias depois, relatou que se sentia confuso, com as lembranças de tudo que viveu nos últimos dias um pouco “esfumaçadas”. Continuava sentindo que todos conseguiam ler seus pensamentos, que vigiavam seus pensamentos. Sentia que, sempre que pensava em fugir do hospital tinha a sensação de que era observado com mais intensidade e de que o cercavam para impedir sua fuga. Ranier então tentava ficar pensando apenas em coisas inofensivas para não chamar atenção da equipe.

Sentia-se muito incomodado durante a noite, pois sentia que observavam constantemente seus pensamentos. Sabia que os outros pacientes dormiam muito durante o dia para poderem observar melhor seus pensamentos durante a noite. Notava também que quando pensava algumas coisas em particular as pessoas tossiam de forma intencional e que quando pensava em se barbear via que algum outro pacientes passava a mão pela face e dizia pra ele que tinha feito a barba. 

Certo dia, ainda internado, teve a pensamento de que isso tudo era uma prova para ver se ele tinha condições de ser um oficial. Entendeu então que que queriam educa-lo a “fazer dele um homem”. 

Percebeu que sempre exigiam dele uma decisão. Certa vez viu um queijo sobre a mesa e notou que havia gotas de líquido sobre o queijo. Com isso teve a certeza de que era um sinal de que ele devia se arriscar. Decidiu então que precisava lutar para mostrar que era não também fisicamente capacitado para ser oficial. Passou então a iniciar brigas com frequência em sua ala. Passou a temer que o mudassem para a ala de pacientes mais tranquilos, pois assim não perderia a oportunidade de mostrar suas capacidades. Pensava sempre “tem que voltar a lutar, tudo está em jogo, exigem isso de você”.  Durante esse período não se sentia humilhado ou deprimido, mas pelo contrário, sentia-se orgulhoso por sentir que era tratado como um inimigo de respeito. Passou a acreditar que sua nação somente poderia durar eternamente se todos homens passassem a ser educados dessa mesma forma que acontecia aqui com ele. E sentia que, se perseverasse, iria conseguir se tornar oficial que desejava.

Depois de alguns dias, entretanto, sentiu que suas forças o deixavam. Não era mais capaz de resistir. Não conversava mais com ninguém. Já não tinha mais esperanças. Estava esperando a morte. Sentia-se acabado física e mentalmente. Sentia haver falhado em definitivamente. Não tinha mais esperanças de ser um dia oficial. 

Antes de sua alta hospitalar o paciente relatava se sentir deprimido, com um sentimento de inferioridade, que não tinha mais valor, que era “como as outras pessoas”. 

Três semanas depois o paciente escreveu uma carta para o médico contando não ter mais o sentimento de que estava sendo observado, que estava feliz por se ver livre desse sentimento. E agradeceu ao médico pela ajuda durante a internação apesar de nunca ter aceitado tal ajuda 


---
